config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users
  resources :properties
end

app/models/property.rb
class Property < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true

  belongs_to :user

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :properties

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def new
    @properties = Property.all
    @property = Property.new
  end

  def create
    @property = current_user.properties.new(property_params)
    if @property.save
      flash[:notice] = "Property successfully added!"
      redirect_to property_path(@property)
    else
      flash[:alert] = "There was a problem saving your property"
      redirect_to new_property_path
    end
  end

  def show
    @property = Property.find(params[:id])
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to root_path
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to property_path(@property)
    else
      render :edit
    end
  end

private
  def property_params
    params.require(:property).permit(:name, :description, :price, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account successfully created!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if @properties.any? %>
  <% @properties.each do |property| %>
    <ul class="list-unstyled">
      <li>
        <%= link_to image_tag(property.photo.url(:thumb)), property_path(property) %>
        <%= link_to property.name, property_path(property) %>
        $<%= property.price %>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirbnbEh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <ul class="nav navbar-nav">
        <%= link_to image_tag('moose.jpg', :class => 'logo navbar-left'), "/" %>
        <li><%= link_to 'Airbnb eh?', root_path %></li>
        <% if user_signed_in? %>
          <li><a>Logged in as <strong><%= current_user.email %></strong></a></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %> </li>
          <% end %>

          <% if user_signed_in? %>
          <li><%= link_to 'Add property', new_property_path %></li>
        <% end %>
      </ul>
    </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  </div>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => 'form-control', :rows => 10 %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div id='photo_upload'>
    <%= f.file_field :photo %>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>You have something you want to change?</h1>

<%= render 'form' %>

app/views/properties/new.html.erb
<h1>Add a New Property</h1>

<%= render 'form' %>

app/views/properties/show.html.erb
<h2><%= @property.name %></h2>
<p><%= image_tag @property.photo.url(:medium) %></p>
<h4><%= @property.description %></h4>
<h4>$<%= @property.price %></h4>

<% if current_user == nil %>
<% elsif @property.user_id == current_user.id %>
  <%= link_to 'Edit', edit_property_path(@property) %>
  <%= link_to 'Delete', property_path(@property),:data => { :method => "delete" } %>
<% end %>